server:
  servlet:
    context-path: /game

spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    version: 1

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml